<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test</title>
        <link rel="stylesheet" href="<?php echo URL ?>theme/default/styles/style.css">
    </head>
    <body>
        <h1>Content-Management-System</h1>
        <h2>Home</h2>
        <a href="<?php echo URL ?>About">About</a>
        <a href="<?php echo URL ?>Admin">Admin</a>
        <a href="<?php echo URL ?>Login">Login</a>
    </body>
</html>
