<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
        <link rel="stylesheet" href="<?php echo URL ?>theme/default/styles/style.css">
    </head>
    <body>
        <h1>Content-Management-System</h1>
        <h2>About</h2>
        <a href="<?php echo URL ?>">Home</a>
        <a href="<?php echo URL ?>Admin">Admin</a>
        <a href="<?php echo URL ?>Login">Login</a>
        <ul>
            <?php foreach ($this->articles as $item): ?>
                <li><?php echo $item['Title']; ?></li>
            <?php endforeach; ?>
        </ul>
    </body>
</html>