<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Novus.io - About</title>
    </head>
    <body>
        <h1>Novus.io</h1>
        <h2>About</h2>
        <a href="<?php echo URL ?>">Home</a>
        <a href="<?php echo URL ?>RestApi/Test">RestApi Test</a>
        <ul>
            <?php foreach ($this->articles as $item): ?>
                <li><?php echo $item['Title']; ?></li>
            <?php endforeach; ?>
        </ul>
    </body>
</html>